// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujvsqmezmnahscjawvsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdnNxbWV6bW5haHNjamF3dnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTE0NDksImV4cCI6MjA2NjY4NzQ0OX0.a8ysbgzPL1g-r6ZDyCgvJAB5Dajqc84HiAOOPhTvvLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);